global using SurveyBasket.Application.Abstractions.Abstractions;
global using SurveyBasket.Application.Abstractions.DTOs.Auth;
global using SurveyBasket.Application.Abstractions.DTOs.Polls.Requests;
global using SurveyBasket.Application.Abstractions.DTOs.Polls.Responses;
global using SurveyBasket.Entities;
global using Microsoft.AspNetCore.Diagnostics;
global using Microsoft.AspNetCore.Http;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.Extensions.Logging;